### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by mtrberzi**

### CODE REVIEW

**Comment by prydom** [comment]
+1 as well. Unrelated to this merge: is there a draft of a separate document that details more transmission and recordings related conduct?

**Comment by pbarfuss** [comment]
+1. So we're good for adopting it now?

Unrelated #1: Seconding prydom's comment about that (incl. Industry Canada and RAC laws, Murphy/Zach probably know more about those than I do).

Unrelated #2: Also we should probably put emergency info somewhere (911 (which you always call FIRST in the event of a medical emergency of any sort, we are in E2 4402, and it's best to go down the stairwell to meet emergency responders), 22222 for Campus Police, whatever Campus Response Team's extension is, and also the nearest AED is in the central hallway on the SECOND FLOOR of Physics (go across on the third floor, then down one floor in PHY) - this is important as AEDs are very good at fixing electrical shock induced cardiac rhythm disturbances).

**Comment by zachomedia** [comment]
Last I heard was Murphy was drafting other policies and would pull request them when they are available for us to review. 

Also, I agree with @pbarfuss of having that info posted. Probably good to also have nearest room on 3rd floor listed. (Might help Campus Police/Emergency responders find us). 
Should also include external Campus Police phone number: (519) 888-4911

**Comment by mtrberzi** [comment]
I'm planning to write up that policy pretty soon and get it posted here; stay tuned. I'll take all of these comments into mind. (I have to spend some time looking through the associated laws, and doing this and that on campus to double-check all physical locations and emergency response phone numbers/personnel.)

**Comment by ehashman** [comment]
@ynasser: ah, I don't know if you were there that day

+1 to the rest of suggestions in the thread, and double +1 to @mtrberzi for taking the initiative on codifying it up! :)

**Pull request merged**
