### PR TITLE
Added IRC and mailing list links

### PR DESCRIPTION
**Pull request by prydom**
This is related to issue #8. Added links to the mailing list over on lists.uwaterloo.ca, to the IRC channel and webchat.

### CODE REVIEW

**Comment by prydom** [comment]
Let me know if we want to link to WICS's IRC tutorial as mentioned during the last meeting.

**Comment by zachomedia** [comment]
Looks good to me.
+1

**Comment by mtrberzi** [comment]
Great, +1

**Comment by ehashman** [comment]
Not sure if the irc:// link will work (doesn't appear to be rendering under GitHub's markdown engine), but I'm fine with merging this and fixing that later if necessary :)

**Comment by ehashman** [comment]
Oh good, the IRC link worked. Deployed and yay!

**Pull request merged**
