### PR TITLE
Redesign of UWARC Website

### PR DESCRIPTION
**Pull request by zachomedia**
This pull request contains a redesign of the UWARC website.

- New overall look and feel
- Added the "club logo"
- Added favicon (Goose head)

Any feedback is welcome.

### CODE REVIEW

**Comment by prydom** [comment]
I reviewed this during development. +1

**Comment by ehashman** [comment]
LOVE it :D

Screenshot for those too lazy to render the site: 
screenshot-5

**Comment by ynasser** [comment]
I find the greyish (?) font a bit hard to read. Also, where is the picture of the goose from?

+1 modulo the font/colour making reading a bit difficult :)

**Comment by ehashman** [comment]
Slightly delayed OMG THE FAVICON YESSS -- visible in screenshot

Re: colors, I would run an accessibility check on the website. Color contrast is often included in those!

**Comment by zachomedia** [comment]
I have darkened the colour of the text
@ynasser can you let me know if this makes it easier to read?

Updated screenshot:

uwarc-screenshot

**Comment by prydom** [comment]
Getting warnings about contrast from https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en (links in header)

**Comment by zachomedia** [comment]
@prydom Thanks, I'll address that (and the missing alt text on the logo).

**Comment by zachomedia** [comment]
Accessibility issues have been addressed.

**Comment by prydom** [comment]
Tests now pass +1

**Comment by ynasser** [comment]
The font is still a bit hard to read. I didn't have problems with the font used on the old site.

**Comment by zachomedia** [comment]
@ynasser I've made the font slightly bigger and darkened it more at http://uwarc.zacharyseguin.ca, can you let me know if this is better (this should be the same as the current site)? If it is, I'll update the PR with it.

**Comment by ynasser** [comment]
Yes, I can read this much more easily.

**Comment by zachomedia** [comment]
@ynasser Thanks.

The PR as been updated with the larger and darker font.

**Comment by ehashman** [comment]
I'd be happy to merge this with another +1 or two.

**Comment by ynasser** [comment]
+1!

**Comment by prydom** [comment]
+1 for the new enhancements (clickable logo and better contrasting fonts)

**Comment by mtrberzi** [comment]
+1.

**Comment by ehashman** [comment]
Merging!

**Pull request merged**
